export type DashboardDict = Record<string, string>;

export const DASHBOARD_I18N: Record<"pt" | "en" | "es" | "fr", DashboardDict> = {
  pt: {
    overview: "Visão Geral",
    analytics: "Analytics",
    projects: "Projetos",
    generate: "Criar",
    chat: "Chat IA",
    hello: "Olá",
    welcome: "Bem-vindo ao seu painel de controle",
    createProject: "Criar Projeto",
    close: "Fechar",
    whatCreate: "O que vamos criar hoje?",
    howHelp: "Como posso te ajudar?",
    totalProjects: "Total de Projetos",
    completed: "Concluídos",
    thisMonth: "este mês",
    topType: "Tipo top",
    usage: "Uso",
    currentPlan: "Plano Atual",
    seePlans: "Ver planos disponíveis",
    recentProjects: "Projetos Recentes",
    seeAll: "Ver todos",
    recentActivity: "Atividade Recente",
    planUsage: "Uso do Plano",
    generations: "Gerações",
    used: "utilizado",
    upgrade: "Fazer upgrade",
    today: "Hoje",
    inProgress: "Em andamento",
    drafts: "Rascunhos",
    advancedAnalytics: "Analytics Avançado",
    analyticsSubtitle: "Desempenho detalhado dos seus projetos",
    completionRate: "Taxa de Conclusão",
    finishedProjects: "Projetos finalizados",
    avgGeneration: "Geração Média",
    perProject: "Gerações por projeto",
    favoriteType: "Tipo Favorito",
    mostCreated: "Projeto mais criado",
    breakdown: "Breakdown por Tipo de Projeto",
    type: "Tipo",
    projectsCol: "Projetos",
    completedCol: "Concluídos",
    rate: "Taxa",
    trend: "Tendência",
    high: "Alta",
    stable: "Estável",
    low: "Baixa",
    allProjects: "Todos os Projetos",
    searchProject: "Buscar projeto...",
    all: "Todos",
    active: "Ativos",
    generating: "Gerando",
    errorStatus: "Erro",
    new: "Novo",
    loadingProjects: "Carregando projetos...",
    noProjects: "Nenhum projeto encontrado.",
    noActivity: "Nenhuma atividade recente.",
    status: "Status",
    date: "Data",
    actions: "Ações",
    name: "Nome",
    projectCompleted: "Projeto concluído",
    projectCreated: "Projeto criado",
    projectGenerating: "Geração em andamento",
    projectFailed: "Falha na geração",
    projectsPerMonth: "Projetos por Mês",
    projectsLast7Days: "Projetos nos Últimos 7 Dias",
    distributionByType: "Distribuição por Tipo",
    noData: "Sem dados",
    breadcrumbRoot: "Dashboard",
    searchCommands: "Buscar comandos…",
    commandPaletteHint: "⌘K",
    aiDockOpen: "Assistente",
    aiDockClose: "Fechar assistente",
    aiDockExpand: "Abrir chat completo",
    dataLoadError: "Não foi possível carregar os dados.",
    retry: "Atualizar",
    libraryOpen: "Biblioteca completa",
    generatingBanner: "Geração em curso — ver em Meus projetos",
    chatLinkProjectHint:
      "Associe um projeto acima para gravar refinamentos no código. Sem projeto, use «Guardar no Dashboard» no chat.",
    tasks: "Tarefas",
    calendar: "Calendário",
    goals: "Metas",
    taskBoardTitle: "Board de Tarefas",
    taskBoardSubtitle: "Organize o sprint — NeuroCode",
    taskBoardNew: "+ Nova tarefa",
    taskBoardAdd: "Adicionar cartão",
    taskColTodo: "A fazer",
    taskColDoing: "Em progresso",
    taskColDone: "Concluído",
    priorityHigh: "Alta",
    priorityMid: "Média",
    priorityLow: "Baixa",
    calendarTitle: "Calendário",
    calendarSubtitle: "Esta semana e próximos marcos",
    calendarNewEvent: "+ Evento",
    calendarThisWeek: "Esta semana",
    calendarUpcoming: "Próximos eventos",
    goalsTitle: "Metas e objetivos",
    goalsSubtitle: "Acompanhe o trimestre",
    goalsMonthly: "Metas do mês",
    goalsQuarter: "OKRs do trimestre",
    goalRevenue: "Receita mensal",
    goalUsers: "Novos usuários",
    goalRetention: "Taxa de retenção",
    goalNps: "NPS",
    okrGrowth: "Crescimento de receita",
    okrUsers: "Expansão de usuários",
    okrProduct: "Excelência do produto",
    goalKrMrr: "Atingir meta de MRR",
    goalKrChurn: "Reduzir churn para <2%",
    goalKrActive: "Metas de usuários ativos",
    goalKrNps: "NPS acima de 60",
    goalKrV3: "Lançar próxima versão principal",
    goalKrUptime: "99,9% de disponibilidade",
    radarTitle: "Performance por área",
    radarSubtitle: "Índice ilustrativo por área",
    radarScore: "Score",
    radar_sales: "Vendas",
    radar_support: "Suporte",
    radar_marketing: "Marketing",
    radar_product: "Produto",
    radar_design: "Design",
    radar_dev: "Dev",
  },
  en: {
    overview: "Overview",
    analytics: "Analytics",
    projects: "Projects",
    generate: "Create",
    chat: "AI Chat",
    hello: "Hello",
    welcome: "Welcome to your control panel",
    createProject: "Create Project",
    close: "Close",
    whatCreate: "What are we building today?",
    howHelp: "How can I help?",
    totalProjects: "Total Projects",
    completed: "Completed",
    thisMonth: "this month",
    topType: "Top type",
    usage: "Usage",
    currentPlan: "Current Plan",
    seePlans: "See available plans",
    recentProjects: "Recent Projects",
    seeAll: "See all",
    recentActivity: "Recent Activity",
    planUsage: "Plan Usage",
    generations: "Generations",
    used: "used",
    upgrade: "Upgrade",
    today: "Today",
    inProgress: "In progress",
    drafts: "Drafts",
    advancedAnalytics: "Advanced Analytics",
    analyticsSubtitle: "Detailed performance of your projects",
    completionRate: "Completion Rate",
    finishedProjects: "Finished projects",
    avgGeneration: "Average Generation",
    perProject: "Generations per project",
    favoriteType: "Favorite Type",
    mostCreated: "Most created project type",
    breakdown: "Project Type Breakdown",
    type: "Type",
    projectsCol: "Projects",
    completedCol: "Completed",
    rate: "Rate",
    trend: "Trend",
    high: "High",
    stable: "Stable",
    low: "Low",
    allProjects: "All Projects",
    searchProject: "Search project...",
    all: "All",
    active: "Active",
    generating: "Generating",
    errorStatus: "Error",
    new: "New",
    loadingProjects: "Loading projects...",
    noProjects: "No projects found.",
    noActivity: "No recent activity.",
    status: "Status",
    date: "Date",
    actions: "Actions",
    name: "Name",
    projectCompleted: "Project completed",
    projectCreated: "Project created",
    projectGenerating: "Generation in progress",
    projectFailed: "Generation failed",
    projectsPerMonth: "Projects per Month",
    projectsLast7Days: "Projects in Last 7 Days",
    distributionByType: "Distribution by Type",
    noData: "No data",
    breadcrumbRoot: "Dashboard",
    searchCommands: "Search commands…",
    commandPaletteHint: "⌘K",
    aiDockOpen: "Assistant",
    aiDockClose: "Close assistant",
    aiDockExpand: "Open full chat",
    dataLoadError: "Could not load data.",
    retry: "Refresh",
    libraryOpen: "Full project library",
    generatingBanner: "Generation in progress — view in My projects",
    chatLinkProjectHint:
      "Link a project above to save code refinements. Without a project, use Save to Dashboard in the chat.",
    tasks: "Tasks",
    calendar: "Calendar",
    goals: "Goals",
    taskBoardTitle: "Task board",
    taskBoardSubtitle: "Sprint planning — NeuroCode",
    taskBoardNew: "+ New task",
    taskBoardAdd: "Add card",
    taskColTodo: "To do",
    taskColDoing: "In progress",
    taskColDone: "Done",
    priorityHigh: "High",
    priorityMid: "Medium",
    priorityLow: "Low",
    calendarTitle: "Calendar",
    calendarSubtitle: "This week and upcoming milestones",
    calendarNewEvent: "+ Event",
    calendarThisWeek: "This week",
    calendarUpcoming: "Upcoming",
    goalsTitle: "Goals and objectives",
    goalsSubtitle: "Quarterly progress",
    goalsMonthly: "Monthly goals",
    goalsQuarter: "Quarterly OKRs",
    goalRevenue: "Monthly revenue",
    goalUsers: "New users",
    goalRetention: "Retention rate",
    goalNps: "NPS",
    okrGrowth: "Revenue growth",
    okrUsers: "User expansion",
    okrProduct: "Product excellence",
    goalKrMrr: "Hit MRR target",
    goalKrChurn: "Reduce churn to <2%",
    goalKrActive: "Active user goals",
    goalKrNps: "NPS above 60",
    goalKrV3: "Ship next major release",
    goalKrUptime: "99.9% uptime",
    radarTitle: "Performance by area",
    radarSubtitle: "Illustrative index by area",
    radarScore: "Score",
    radar_sales: "Sales",
    radar_support: "Support",
    radar_marketing: "Marketing",
    radar_product: "Product",
    radar_design: "Design",
    radar_dev: "Engineering",
  },
  es: {
    overview: "Resumen",
    analytics: "Analítica",
    projects: "Proyectos",
    generate: "Crear",
    chat: "Chat IA",
    hello: "Hola",
    welcome: "Bienvenido a tu panel de control",
    createProject: "Crear Proyecto",
    close: "Cerrar",
    whatCreate: "¿Qué vamos a crear hoy?",
    howHelp: "¿Cómo puedo ayudarte?",
    totalProjects: "Total de Proyectos",
    completed: "Completados",
    thisMonth: "este mes",
    topType: "Tipo principal",
    usage: "Uso",
    currentPlan: "Plan Actual",
    seePlans: "Ver planes disponibles",
    recentProjects: "Proyectos Recientes",
    seeAll: "Ver todos",
    recentActivity: "Actividad Reciente",
    planUsage: "Uso del Plan",
    generations: "Generaciones",
    used: "usado",
    upgrade: "Mejorar plan",
    today: "Hoy",
    inProgress: "En progreso",
    drafts: "Borradores",
    advancedAnalytics: "Analítica Avanzada",
    analyticsSubtitle: "Rendimiento detallado de tus proyectos",
    completionRate: "Tasa de Finalización",
    finishedProjects: "Proyectos finalizados",
    avgGeneration: "Generación Promedio",
    perProject: "Generaciones por proyecto",
    favoriteType: "Tipo Favorito",
    mostCreated: "Tipo más creado",
    breakdown: "Desglose por Tipo de Proyecto",
    type: "Tipo",
    projectsCol: "Proyectos",
    completedCol: "Completados",
    rate: "Tasa",
    trend: "Tendencia",
    high: "Alta",
    stable: "Estable",
    low: "Baja",
    allProjects: "Todos los Proyectos",
    searchProject: "Buscar proyecto...",
    all: "Todos",
    active: "Activos",
    generating: "Generando",
    errorStatus: "Error",
    new: "Nuevo",
    loadingProjects: "Cargando proyectos...",
    noProjects: "No se encontraron proyectos.",
    noActivity: "Sin actividad reciente.",
    status: "Estado",
    date: "Fecha",
    actions: "Acciones",
    name: "Nombre",
    projectCompleted: "Proyecto completado",
    projectCreated: "Proyecto creado",
    projectGenerating: "Generación en curso",
    projectFailed: "Error en la generación",
    projectsPerMonth: "Proyectos por Mes",
    projectsLast7Days: "Proyectos en los Últimos 7 Días",
    distributionByType: "Distribución por Tipo",
    noData: "Sin datos",
    breadcrumbRoot: "Panel",
    searchCommands: "Buscar comandos…",
    commandPaletteHint: "⌘K",
    aiDockOpen: "Asistente",
    aiDockClose: "Cerrar asistente",
    aiDockExpand: "Abrir chat completo",
    dataLoadError: "No se pudieron cargar los datos.",
    retry: "Actualizar",
    libraryOpen: "Biblioteca completa",
    generatingBanner: "Generación en curso — ver en Mis proyectos",
    chatLinkProjectHint:
      "Vincula un proyecto arriba para guardar refinamientos en el código. Sin proyecto, usa Guardar en el panel en el chat.",
    tasks: "Tareas",
    calendar: "Calendario",
    goals: "Metas",
    taskBoardTitle: "Tablero de tareas",
    taskBoardSubtitle: "Sprint — NeuroCode",
    taskBoardNew: "+ Nueva tarea",
    taskBoardAdd: "Añadir tarjeta",
    taskColTodo: "Por hacer",
    taskColDoing: "En curso",
    taskColDone: "Hecho",
    priorityHigh: "Alta",
    priorityMid: "Media",
    priorityLow: "Baja",
    calendarTitle: "Calendario",
    calendarSubtitle: "Esta semana y próximos hitos",
    calendarNewEvent: "+ Evento",
    calendarThisWeek: "Esta semana",
    calendarUpcoming: "Próximos eventos",
    goalsTitle: "Metas y objetivos",
    goalsSubtitle: "Progreso del trimestre",
    goalsMonthly: "Metas del mes",
    goalsQuarter: "OKRs del trimestre",
    goalRevenue: "Ingresos mensuales",
    goalUsers: "Nuevos usuarios",
    goalRetention: "Tasa de retención",
    goalNps: "NPS",
    okrGrowth: "Crecimiento de ingresos",
    okrUsers: "Expansión de usuarios",
    okrProduct: "Excelencia del producto",
    goalKrMrr: "Alcanzar objetivo MRR",
    goalKrChurn: "Reducir churn a <2%",
    goalKrActive: "Metas de usuarios activos",
    goalKrNps: "NPS por encima de 60",
    goalKrV3: "Lanzar próxima versión mayor",
    goalKrUptime: "99,9% de disponibilidad",
    radarTitle: "Rendimiento por área",
    radarSubtitle: "Índice ilustrativo por área",
    radarScore: "Puntuación",
    radar_sales: "Ventas",
    radar_support: "Soporte",
    radar_marketing: "Marketing",
    radar_product: "Producto",
    radar_design: "Diseño",
    radar_dev: "Desarrollo",
  },
  fr: {
    overview: "Vue d'ensemble",
    analytics: "Analytique",
    projects: "Projets",
    generate: "Créer",
    chat: "Chat IA",
    hello: "Bonjour",
    welcome: "Bienvenue sur votre tableau de bord",
    createProject: "Créer un Projet",
    close: "Fermer",
    whatCreate: "Que créons-nous aujourd'hui ?",
    howHelp: "Comment puis-je vous aider ?",
    totalProjects: "Total des Projets",
    completed: "Terminés",
    thisMonth: "ce mois-ci",
    topType: "Type principal",
    usage: "Utilisation",
    currentPlan: "Plan Actuel",
    seePlans: "Voir les plans",
    recentProjects: "Projets Récents",
    seeAll: "Voir tout",
    recentActivity: "Activité Récente",
    planUsage: "Utilisation du Plan",
    generations: "Générations",
    used: "utilisé",
    upgrade: "Passer au niveau supérieur",
    today: "Aujourd'hui",
    inProgress: "En cours",
    drafts: "Brouillons",
    advancedAnalytics: "Analytique Avancée",
    analyticsSubtitle: "Performance détaillée de vos projets",
    completionRate: "Taux de Finalisation",
    finishedProjects: "Projets finalisés",
    avgGeneration: "Génération Moyenne",
    perProject: "Générations par projet",
    favoriteType: "Type Favori",
    mostCreated: "Type le plus créé",
    breakdown: "Répartition par Type de Projet",
    type: "Type",
    projectsCol: "Projets",
    completedCol: "Terminés",
    rate: "Taux",
    trend: "Tendance",
    high: "Élevée",
    stable: "Stable",
    low: "Faible",
    allProjects: "Tous les Projets",
    searchProject: "Rechercher un projet...",
    all: "Tous",
    active: "Actifs",
    generating: "En cours",
    errorStatus: "Erreur",
    new: "Nouveau",
    loadingProjects: "Chargement des projets...",
    noProjects: "Aucun projet trouvé.",
    noActivity: "Aucune activité récente.",
    status: "Statut",
    date: "Date",
    actions: "Actions",
    name: "Nom",
    projectCompleted: "Projet terminé",
    projectCreated: "Projet créé",
    projectGenerating: "Génération en cours",
    projectFailed: "Échec de la génération",
    projectsPerMonth: "Projets par Mois",
    projectsLast7Days: "Projets sur 7 Jours",
    distributionByType: "Répartition par Type",
    noData: "Pas de données",
    breadcrumbRoot: "Tableau de bord",
    searchCommands: "Rechercher des commandes…",
    commandPaletteHint: "⌘K",
    aiDockOpen: "Assistant",
    aiDockClose: "Fermer l'assistant",
    aiDockExpand: "Ouvrir le chat complet",
    dataLoadError: "Impossible de charger les données.",
    retry: "Actualiser",
    libraryOpen: "Bibliothèque complète",
    generatingBanner: "Génération en cours — voir dans Mes projets",
    chatLinkProjectHint:
      "Associez un projet ci-dessus pour enregistrer le code affiné. Sans projet, utilisez Enregistrer dans le tableau de bord dans le chat.",
    tasks: "Tâches",
    calendar: "Calendrier",
    goals: "Objectifs",
    taskBoardTitle: "Tableau des tâches",
    taskBoardSubtitle: "Sprint — NeuroCode",
    taskBoardNew: "+ Nouvelle tâche",
    taskBoardAdd: "Ajouter une carte",
    taskColTodo: "À faire",
    taskColDoing: "En cours",
    taskColDone: "Terminé",
    priorityHigh: "Haute",
    priorityMid: "Moyenne",
    priorityLow: "Basse",
    calendarTitle: "Calendrier",
    calendarSubtitle: "Cette semaine et jalons à venir",
    calendarNewEvent: "+ Événement",
    calendarThisWeek: "Cette semaine",
    calendarUpcoming: "À venir",
    goalsTitle: "Objectifs",
    goalsSubtitle: "Progrès du trimestre",
    goalsMonthly: "Objectifs du mois",
    goalsQuarter: "OKR du trimestre",
    goalRevenue: "Revenu mensuel",
    goalUsers: "Nouveaux utilisateurs",
    goalRetention: "Rétention",
    goalNps: "NPS",
    okrGrowth: "Croissance des revenus",
    okrUsers: "Expansion utilisateurs",
    okrProduct: "Excellence produit",
    goalKrMrr: "Atteindre l'objectif MRR",
    goalKrChurn: "Réduire le churn à <2%",
    goalKrActive: "Objectifs utilisateurs actifs",
    goalKrNps: "NPS supérieur à 60",
    goalKrV3: "Lancer la prochaine version majeure",
    goalKrUptime: "99,9% de disponibilité",
    radarTitle: "Performance par domaine",
    radarSubtitle: "Indice illustratif par domaine",
    radarScore: "Score",
    radar_sales: "Ventes",
    radar_support: "Support",
    radar_marketing: "Marketing",
    radar_product: "Produit",
    radar_design: "Design",
    radar_dev: "Développement",
  },
};

export function dashboardStatusLabel(status: string, i: DashboardDict) {
  if (status === "completed") return i.completed;
  if (status === "generating") return i.generating;
  if (status === "error") return i.errorStatus;
  if (status === "draft") return i.drafts;
  if (status === "active") return i.active;
  return status;
}

export function dashboardStatusBadge(status: string) {
  const map: Record<string, string> = {
    completed: "bg-gold/15 text-gold border border-gold/25",
    generating: "bg-sky-50 text-sky-700 border border-sky-200",
    error: "bg-red-50 text-red-700 border border-red-200",
    draft: "bg-ink/[0.05] text-ink-35 border border-ink-15",
    active: "bg-blue-50 text-blue-600 border border-blue-200",
  };
  return map[status] ?? map.draft;
}
