/** Keep in sync with `Language` in `@/context/language-context` */
export type HeroDemoLanguage = "pt" | "en" | "es" | "fr";

/** Minified iframe previews for the hero live demo — one triple per language */
export const HERO_DEMO_PREVIEW_HTML: Record<
  HeroDemoLanguage,
  readonly [string, string, string]
> = {
  pt: [
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#0d0d0d;color:#f5f5f5;min-height:100vh;display:flex;flex-direction:column}nav{padding:12px 20px;border-bottom:1px solid #ff6b6b22;font-size:11px;color:#ff6b6b;letter-spacing:3px;text-transform:uppercase;display:flex;align-items:center;gap:8px}nav b{color:white;font-size:13px}.hero{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;background:radial-gradient(ellipse at 50% 60%,#2d0a0a,#0d0d0d);text-align:center;padding:20px;gap:12px}h1{font-size:clamp(1.8rem,6vw,3.5rem);color:#ff6b6b;font-weight:300;letter-spacing:2px}p{color:#ffffff66;font-size:12px;max-width:260px;line-height:1.5}.btns{display:flex;gap:10px;margin-top:8px}.btn{padding:8px 18px;border-radius:4px;font-size:11px;letter-spacing:2px;text-transform:uppercase;cursor:pointer}.b1{background:transparent;border:1px solid #ff6b6b;color:#ff6b6b}.b2{background:#ff6b6b;border:1px solid #ff6b6b;color:white}.dishes{display:flex;gap:8px;margin-top:16px}.dish{background:#ffffff08;border:1px solid #ffffff11;border-radius:8px;padding:8px 14px;font-size:20px}</style></head><body><nav><b>🌸 SAKURA</b> · Restaurante Japonês</nav><div class="hero"><h1>Sabores do Japão</h1><p>Culinária japonesa autêntica no coração de São Paulo</p><div class="btns"><div class="btn b1">Ver Menu</div><div class="btn b2">Reservar Mesa</div></div><div class="dishes"><div class="dish">🍣</div><div class="dish">🍜</div><div class="dish">🥢</div></div></div></body></html>`,
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#0a0a0f;color:#e2e8f0;min-height:100vh;padding:14px;font-size:11px}header{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px;padding-bottom:10px;border-bottom:1px solid #1e293b}.logo{color:#10b981;font-weight:700;font-size:12px;letter-spacing:2px}.badge{background:#10b98115;color:#10b981;padding:2px 7px;border-radius:20px;font-size:9px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-bottom:10px}.stat{background:#0d1117;border:1px solid #1e293b;border-radius:7px;padding:9px}.stat-val{font-size:15px;font-weight:700;color:white;margin-bottom:2px}.stat-lbl{color:#64748b;font-size:8px;text-transform:uppercase;letter-spacing:1px}.stat-up{color:#10b981;font-size:8px;margin-top:2px}.stat-dn{color:#f43f5e;font-size:8px;margin-top:2px}.chart-wrap{background:#0d1117;border:1px solid #1e293b;border-radius:7px;padding:9px}.chart-title{color:#64748b;font-size:8px;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px}.chart{display:flex;align-items:flex-end;gap:3px;height:64px}.bar{flex:1;border-radius:3px 3px 0 0;min-height:6px;background:linear-gradient(to top,#10b981,#10b98133)}</style></head><body><header><span class="logo">⚡ ANALYTICS</span><span class="badge">● LIVE</span></header><div class="stats"><div class="stat"><div class="stat-val">R$48k</div><div class="stat-lbl">MRR</div><div class="stat-up">↑ +12%</div></div><div class="stat"><div class="stat-val">1.847</div><div class="stat-lbl">Usuários</div><div class="stat-up">↑ +8%</div></div><div class="stat"><div class="stat-val">2.4%</div><div class="stat-lbl">Churn</div><div class="stat-dn">↓ -0.3%</div></div><div class="stat"><div class="stat-val">78</div><div class="stat-lbl">NPS</div><div class="stat-up">↑ +5</div></div></div><div class="chart-wrap"><div class="chart-title">Receita mensal · 2025</div><div class="chart"><div class="bar" style="height:32%"></div><div class="bar" style="height:42%"></div><div class="bar" style="height:36%"></div><div class="bar" style="height:50%"></div><div class="bar" style="height:58%"></div><div class="bar" style="height:54%"></div><div class="bar" style="height:70%"></div><div class="bar" style="height:65%"></div><div class="bar" style="height:78%"></div><div class="bar" style="height:83%"></div><div class="bar" style="height:88%"></div><div class="bar" style="height:95%;background:linear-gradient(to top,#f59e0b,#f59e0b33)"></div></div></div></body></html>`,
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#f8fafc;min-height:100vh;font-size:11px}nav{background:white;border-bottom:1px solid #e2e8f0;padding:9px 14px;display:flex;align-items:center;justify-content:space-between}.logo{font-weight:800;color:#6366f1;font-size:12px}.nav-btn{background:#6366f1;color:white;padding:4px 10px;border-radius:5px;font-size:9px;font-weight:600}.hero{background:linear-gradient(135deg,#6366f1,#8b5cf6);color:white;padding:20px 14px;text-align:center}.hero h1{font-size:16px;font-weight:800;margin-bottom:5px}.hero p{font-size:10px;opacity:.8;margin-bottom:10px}.hero-cta{display:inline-block;background:white;color:#6366f1;padding:6px 16px;border-radius:7px;font-size:10px;font-weight:700}.grid{padding:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.card{background:white;border-radius:7px;overflow:hidden;border:1px solid #e2e8f0;box-shadow:0 1px 3px #0000000d}.card-thumb{height:40px;display:flex;align-items:center;justify-content:center;font-size:18px}.card-body{padding:7px}.card-name{font-size:10px;font-weight:700;color:#1e293b;margin-bottom:2px}.card-meta{font-size:8px;color:#94a3b8;margin-bottom:3px}.card-row{display:flex;align-items:center;justify-content:space-between}.card-price{font-size:11px;font-weight:800;color:#6366f1}.badge{background:#dcfce7;color:#16a34a;padding:1px 5px;border-radius:9px;font-size:7px;font-weight:700}</style></head><body><nav><span class="logo">⚡ EduPlatform</span><span class="nav-btn">Acessar</span></nav><div class="hero"><h1>Aprenda sem limites</h1><p>200+ cursos em tecnologia, negócios e design</p><span class="hero-cta">Ver todos os cursos →</span></div><div class="grid"><div class="card"><div class="card-thumb" style="background:#fef3c7">📱</div><div class="card-body"><div class="card-name">React Native Pro</div><div class="card-meta">42 aulas · 8h</div><div class="card-row"><span class="card-price">R$197</span><span class="badge">NOVO</span></div></div></div><div class="card"><div class="card-thumb" style="background:#dbeafe">🤖</div><div class="card-body"><div class="card-name">IA para Negócios</div><div class="card-meta">28 aulas · 5h</div><div class="card-row"><span class="card-price">R$147</span><span class="badge">★ 4.9</span></div></div></div><div class="card"><div class="card-thumb" style="background:#f3e8ff">💰</div><div class="card-body"><div class="card-name">SaaS do Zero</div><div class="card-meta">56 aulas · 12h</div><div class="card-row"><span class="card-price">R$297</span><span class="badge">TOP</span></div></div></div></div></body></html>`,
  ],
  en: [
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#0d0d0d;color:#f5f5f5;min-height:100vh;display:flex;flex-direction:column}nav{padding:12px 20px;border-bottom:1px solid #ff6b6b22;font-size:11px;color:#ff6b6b;letter-spacing:3px;text-transform:uppercase;display:flex;align-items:center;gap:8px}nav b{color:white;font-size:13px}.hero{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;background:radial-gradient(ellipse at 50% 60%,#2d0a0a,#0d0d0d);text-align:center;padding:20px;gap:12px}h1{font-size:clamp(1.8rem,6vw,3.5rem);color:#ff6b6b;font-weight:300;letter-spacing:2px}p{color:#ffffff66;font-size:12px;max-width:260px;line-height:1.5}.btns{display:flex;gap:10px;margin-top:8px}.btn{padding:8px 18px;border-radius:4px;font-size:11px;letter-spacing:2px;text-transform:uppercase;cursor:pointer}.b1{background:transparent;border:1px solid #ff6b6b;color:#ff6b6b}.b2{background:#ff6b6b;border:1px solid #ff6b6b;color:white}.dishes{display:flex;gap:8px;margin-top:16px}.dish{background:#ffffff08;border:1px solid #ffffff11;border-radius:8px;padding:8px 14px;font-size:20px}</style></head><body><nav><b>🌸 SAKURA</b> · Japanese Restaurant</nav><div class="hero"><h1>Flavors of Japan</h1><p>Authentic Japanese cuisine in the heart of the city</p><div class="btns"><div class="btn b1">View Menu</div><div class="btn b2">Book a Table</div></div><div class="dishes"><div class="dish">🍣</div><div class="dish">🍜</div><div class="dish">🥢</div></div></div></body></html>`,
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#0a0a0f;color:#e2e8f0;min-height:100vh;padding:14px;font-size:11px}header{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px;padding-bottom:10px;border-bottom:1px solid #1e293b}.logo{color:#10b981;font-weight:700;font-size:12px;letter-spacing:2px}.badge{background:#10b98115;color:#10b981;padding:2px 7px;border-radius:20px;font-size:9px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-bottom:10px}.stat{background:#0d1117;border:1px solid #1e293b;border-radius:7px;padding:9px}.stat-val{font-size:15px;font-weight:700;color:white;margin-bottom:2px}.stat-lbl{color:#64748b;font-size:8px;text-transform:uppercase;letter-spacing:1px}.stat-up{color:#10b981;font-size:8px;margin-top:2px}.stat-dn{color:#f43f5e;font-size:8px;margin-top:2px}.chart-wrap{background:#0d1117;border:1px solid #1e293b;border-radius:7px;padding:9px}.chart-title{color:#64748b;font-size:8px;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px}.chart{display:flex;align-items:flex-end;gap:3px;height:64px}.bar{flex:1;border-radius:3px 3px 0 0;min-height:6px;background:linear-gradient(to top,#10b981,#10b98133)}</style></head><body><header><span class="logo">⚡ ANALYTICS</span><span class="badge">● LIVE</span></header><div class="stats"><div class="stat"><div class="stat-val">$48k</div><div class="stat-lbl">MRR</div><div class="stat-up">↑ +12%</div></div><div class="stat"><div class="stat-val">1,847</div><div class="stat-lbl">Users</div><div class="stat-up">↑ +8%</div></div><div class="stat"><div class="stat-val">2.4%</div><div class="stat-lbl">Churn</div><div class="stat-dn">↓ -0.3%</div></div><div class="stat"><div class="stat-val">78</div><div class="stat-lbl">NPS</div><div class="stat-up">↑ +5</div></div></div><div class="chart-wrap"><div class="chart-title">Monthly revenue · 2025</div><div class="chart"><div class="bar" style="height:32%"></div><div class="bar" style="height:42%"></div><div class="bar" style="height:36%"></div><div class="bar" style="height:50%"></div><div class="bar" style="height:58%"></div><div class="bar" style="height:54%"></div><div class="bar" style="height:70%"></div><div class="bar" style="height:65%"></div><div class="bar" style="height:78%"></div><div class="bar" style="height:83%"></div><div class="bar" style="height:88%"></div><div class="bar" style="height:95%;background:linear-gradient(to top,#f59e0b,#f59e0b33)"></div></div></div></body></html>`,
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#f8fafc;min-height:100vh;font-size:11px}nav{background:white;border-bottom:1px solid #e2e8f0;padding:9px 14px;display:flex;align-items:center;justify-content:space-between}.logo{font-weight:800;color:#6366f1;font-size:12px}.nav-btn{background:#6366f1;color:white;padding:4px 10px;border-radius:5px;font-size:9px;font-weight:600}.hero{background:linear-gradient(135deg,#6366f1,#8b5cf6);color:white;padding:20px 14px;text-align:center}.hero h1{font-size:16px;font-weight:800;margin-bottom:5px}.hero p{font-size:10px;opacity:.8;margin-bottom:10px}.hero-cta{display:inline-block;background:white;color:#6366f1;padding:6px 16px;border-radius:7px;font-size:10px;font-weight:700}.grid{padding:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.card{background:white;border-radius:7px;overflow:hidden;border:1px solid #e2e8f0;box-shadow:0 1px 3px #0000000d}.card-thumb{height:40px;display:flex;align-items:center;justify-content:center;font-size:18px}.card-body{padding:7px}.card-name{font-size:10px;font-weight:700;color:#1e293b;margin-bottom:2px}.card-meta{font-size:8px;color:#94a3b8;margin-bottom:3px}.card-row{display:flex;align-items:center;justify-content:space-between}.card-price{font-size:11px;font-weight:800;color:#6366f1}.badge{background:#dcfce7;color:#16a34a;padding:1px 5px;border-radius:9px;font-size:7px;font-weight:700}</style></head><body><nav><span class="logo">⚡ EduPlatform</span><span class="nav-btn">Sign in</span></nav><div class="hero"><h1>Learn without limits</h1><p>200+ courses in tech, business and design</p><span class="hero-cta">See all courses →</span></div><div class="grid"><div class="card"><div class="card-thumb" style="background:#fef3c7">📱</div><div class="card-body"><div class="card-name">React Native Pro</div><div class="card-meta">42 lessons · 8h</div><div class="card-row"><span class="card-price">$197</span><span class="badge">NEW</span></div></div></div><div class="card"><div class="card-thumb" style="background:#dbeafe">🤖</div><div class="card-body"><div class="card-name">AI for Business</div><div class="card-meta">28 lessons · 5h</div><div class="card-row"><span class="card-price">$147</span><span class="badge">★ 4.9</span></div></div></div><div class="card"><div class="card-thumb" style="background:#f3e8ff">💰</div><div class="card-body"><div class="card-name">SaaS from Scratch</div><div class="card-meta">56 lessons · 12h</div><div class="card-row"><span class="card-price">$297</span><span class="badge">TOP</span></div></div></div></div></body></html>`,
  ],
  es: [
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#0d0d0d;color:#f5f5f5;min-height:100vh;display:flex;flex-direction:column}nav{padding:12px 20px;border-bottom:1px solid #ff6b6b22;font-size:11px;color:#ff6b6b;letter-spacing:3px;text-transform:uppercase;display:flex;align-items:center;gap:8px}nav b{color:white;font-size:13px}.hero{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;background:radial-gradient(ellipse at 50% 60%,#2d0a0a,#0d0d0d);text-align:center;padding:20px;gap:12px}h1{font-size:clamp(1.8rem,6vw,3.5rem);color:#ff6b6b;font-weight:300;letter-spacing:2px}p{color:#ffffff66;font-size:12px;max-width:260px;line-height:1.5}.btns{display:flex;gap:10px;margin-top:8px}.btn{padding:8px 18px;border-radius:4px;font-size:11px;letter-spacing:2px;text-transform:uppercase;cursor:pointer}.b1{background:transparent;border:1px solid #ff6b6b;color:#ff6b6b}.b2{background:#ff6b6b;border:1px solid #ff6b6b;color:white}.dishes{display:flex;gap:8px;margin-top:16px}.dish{background:#ffffff08;border:1px solid #ffffff11;border-radius:8px;padding:8px 14px;font-size:20px}</style></head><body><nav><b>🌸 SAKURA</b> · Restaurante Japonés</nav><div class="hero"><h1>Sabores de Japón</h1><p>Cocina japonesa auténtica en el corazón de la ciudad</p><div class="btns"><div class="btn b1">Ver carta</div><div class="btn b2">Reservar mesa</div></div><div class="dishes"><div class="dish">🍣</div><div class="dish">🍜</div><div class="dish">🥢</div></div></div></body></html>`,
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#0a0a0f;color:#e2e8f0;min-height:100vh;padding:14px;font-size:11px}header{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px;padding-bottom:10px;border-bottom:1px solid #1e293b}.logo{color:#10b981;font-weight:700;font-size:12px;letter-spacing:2px}.badge{background:#10b98115;color:#10b981;padding:2px 7px;border-radius:20px;font-size:9px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-bottom:10px}.stat{background:#0d1117;border:1px solid #1e293b;border-radius:7px;padding:9px}.stat-val{font-size:15px;font-weight:700;color:white;margin-bottom:2px}.stat-lbl{color:#64748b;font-size:8px;text-transform:uppercase;letter-spacing:1px}.stat-up{color:#10b981;font-size:8px;margin-top:2px}.stat-dn{color:#f43f5e;font-size:8px;margin-top:2px}.chart-wrap{background:#0d1117;border:1px solid #1e293b;border-radius:7px;padding:9px}.chart-title{color:#64748b;font-size:8px;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px}.chart{display:flex;align-items:flex-end;gap:3px;height:64px}.bar{flex:1;border-radius:3px 3px 0 0;min-height:6px;background:linear-gradient(to top,#10b981,#10b98133)}</style></head><body><header><span class="logo">⚡ ANALYTICS</span><span class="badge">● LIVE</span></header><div class="stats"><div class="stat"><div class="stat-val">48k €</div><div class="stat-lbl">MRR</div><div class="stat-up">↑ +12%</div></div><div class="stat"><div class="stat-val">1.847</div><div class="stat-lbl">Usuarios</div><div class="stat-up">↑ +8%</div></div><div class="stat"><div class="stat-val">2,4%</div><div class="stat-lbl">Churn</div><div class="stat-dn">↓ -0,3%</div></div><div class="stat"><div class="stat-val">78</div><div class="stat-lbl">NPS</div><div class="stat-up">↑ +5</div></div></div><div class="chart-wrap"><div class="chart-title">Ingresos mensuales · 2025</div><div class="chart"><div class="bar" style="height:32%"></div><div class="bar" style="height:42%"></div><div class="bar" style="height:36%"></div><div class="bar" style="height:50%"></div><div class="bar" style="height:58%"></div><div class="bar" style="height:54%"></div><div class="bar" style="height:70%"></div><div class="bar" style="height:65%"></div><div class="bar" style="height:78%"></div><div class="bar" style="height:83%"></div><div class="bar" style="height:88%"></div><div class="bar" style="height:95%;background:linear-gradient(to top,#f59e0b,#f59e0b33)"></div></div></div></body></html>`,
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#f8fafc;min-height:100vh;font-size:11px}nav{background:white;border-bottom:1px solid #e2e8f0;padding:9px 14px;display:flex;align-items:center;justify-content:space-between}.logo{font-weight:800;color:#6366f1;font-size:12px}.nav-btn{background:#6366f1;color:white;padding:4px 10px;border-radius:5px;font-size:9px;font-weight:600}.hero{background:linear-gradient(135deg,#6366f1,#8b5cf6);color:white;padding:20px 14px;text-align:center}.hero h1{font-size:16px;font-weight:800;margin-bottom:5px}.hero p{font-size:10px;opacity:.8;margin-bottom:10px}.hero-cta{display:inline-block;background:white;color:#6366f1;padding:6px 16px;border-radius:7px;font-size:10px;font-weight:700}.grid{padding:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.card{background:white;border-radius:7px;overflow:hidden;border:1px solid #e2e8f0;box-shadow:0 1px 3px #0000000d}.card-thumb{height:40px;display:flex;align-items:center;justify-content:center;font-size:18px}.card-body{padding:7px}.card-name{font-size:10px;font-weight:700;color:#1e293b;margin-bottom:2px}.card-meta{font-size:8px;color:#94a3b8;margin-bottom:3px}.card-row{display:flex;align-items:center;justify-content:space-between}.card-price{font-size:11px;font-weight:800;color:#6366f1}.badge{background:#dcfce7;color:#16a34a;padding:1px 5px;border-radius:9px;font-size:7px;font-weight:700}</style></head><body><nav><span class="logo">⚡ EduPlatform</span><span class="nav-btn">Entrar</span></nav><div class="hero"><h1>Aprende sin límites</h1><p>Más de 200 cursos en tecnología, negocios y diseño</p><span class="hero-cta">Ver todos los cursos →</span></div><div class="grid"><div class="card"><div class="card-thumb" style="background:#fef3c7">📱</div><div class="card-body"><div class="card-name">React Native Pro</div><div class="card-meta">42 clases · 8h</div><div class="card-row"><span class="card-price">197 €</span><span class="badge">NUEVO</span></div></div></div><div class="card"><div class="card-thumb" style="background:#dbeafe">🤖</div><div class="card-body"><div class="card-name">IA para negocios</div><div class="card-meta">28 clases · 5h</div><div class="card-row"><span class="card-price">147 €</span><span class="badge">★ 4,9</span></div></div></div><div class="card"><div class="card-thumb" style="background:#f3e8ff">💰</div><div class="card-body"><div class="card-name">SaaS desde cero</div><div class="card-meta">56 clases · 12h</div><div class="card-row"><span class="card-price">297 €</span><span class="badge">TOP</span></div></div></div></div></body></html>`,
  ],
  fr: [
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#0d0d0d;color:#f5f5f5;min-height:100vh;display:flex;flex-direction:column}nav{padding:12px 20px;border-bottom:1px solid #ff6b6b22;font-size:11px;color:#ff6b6b;letter-spacing:3px;text-transform:uppercase;display:flex;align-items:center;gap:8px}nav b{color:white;font-size:13px}.hero{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;background:radial-gradient(ellipse at 50% 60%,#2d0a0a,#0d0d0d);text-align:center;padding:20px;gap:12px}h1{font-size:clamp(1.8rem,6vw,3.5rem);color:#ff6b6b;font-weight:300;letter-spacing:2px}p{color:#ffffff66;font-size:12px;max-width:260px;line-height:1.5}.btns{display:flex;gap:10px;margin-top:8px}.btn{padding:8px 18px;border-radius:4px;font-size:11px;letter-spacing:2px;text-transform:uppercase;cursor:pointer}.b1{background:transparent;border:1px solid #ff6b6b;color:#ff6b6b}.b2{background:#ff6b6b;border:1px solid #ff6b6b;color:white}.dishes{display:flex;gap:8px;margin-top:16px}.dish{background:#ffffff08;border:1px solid #ffffff11;border-radius:8px;padding:8px 14px;font-size:20px}</style></head><body><nav><b>🌸 SAKURA</b> · Restaurant japonais</nav><div class="hero"><h1>Saveurs du Japon</h1><p>Cuisine japonaise authentique au cœur de la ville</p><div class="btns"><div class="btn b1">Voir la carte</div><div class="btn b2">Réserver</div></div><div class="dishes"><div class="dish">🍣</div><div class="dish">🍜</div><div class="dish">🥢</div></div></div></body></html>`,
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#0a0a0f;color:#e2e8f0;min-height:100vh;padding:14px;font-size:11px}header{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px;padding-bottom:10px;border-bottom:1px solid #1e293b}.logo{color:#10b981;font-weight:700;font-size:12px;letter-spacing:2px}.badge{background:#10b98115;color:#10b981;padding:2px 7px;border-radius:20px;font-size:9px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-bottom:10px}.stat{background:#0d1117;border:1px solid #1e293b;border-radius:7px;padding:9px}.stat-val{font-size:15px;font-weight:700;color:white;margin-bottom:2px}.stat-lbl{color:#64748b;font-size:8px;text-transform:uppercase;letter-spacing:1px}.stat-up{color:#10b981;font-size:8px;margin-top:2px}.stat-dn{color:#f43f5e;font-size:8px;margin-top:2px}.chart-wrap{background:#0d1117;border:1px solid #1e293b;border-radius:7px;padding:9px}.chart-title{color:#64748b;font-size:8px;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px}.chart{display:flex;align-items:flex-end;gap:3px;height:64px}.bar{flex:1;border-radius:3px 3px 0 0;min-height:6px;background:linear-gradient(to top,#10b981,#10b98133)}</style></head><body><header><span class="logo">⚡ ANALYTICS</span><span class="badge">● LIVE</span></header><div class="stats"><div class="stat"><div class="stat-val">48k €</div><div class="stat-lbl">MRR</div><div class="stat-up">↑ +12%</div></div><div class="stat"><div class="stat-val">1 847</div><div class="stat-lbl">Utilisateurs</div><div class="stat-up">↑ +8%</div></div><div class="stat"><div class="stat-val">2,4%</div><div class="stat-lbl">Churn</div><div class="stat-dn">↓ -0,3%</div></div><div class="stat"><div class="stat-val">78</div><div class="stat-lbl">NPS</div><div class="stat-up">↑ +5</div></div></div><div class="chart-wrap"><div class="chart-title">Revenu mensuel · 2025</div><div class="chart"><div class="bar" style="height:32%"></div><div class="bar" style="height:42%"></div><div class="bar" style="height:36%"></div><div class="bar" style="height:50%"></div><div class="bar" style="height:58%"></div><div class="bar" style="height:54%"></div><div class="bar" style="height:70%"></div><div class="bar" style="height:65%"></div><div class="bar" style="height:78%"></div><div class="bar" style="height:83%"></div><div class="bar" style="height:88%"></div><div class="bar" style="height:95%;background:linear-gradient(to top,#f59e0b,#f59e0b33)"></div></div></div></body></html>`,
    `<!DOCTYPE html><html><head><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui,sans-serif}body{background:#f8fafc;min-height:100vh;font-size:11px}nav{background:white;border-bottom:1px solid #e2e8f0;padding:9px 14px;display:flex;align-items:center;justify-content:space-between}.logo{font-weight:800;color:#6366f1;font-size:12px}.nav-btn{background:#6366f1;color:white;padding:4px 10px;border-radius:5px;font-size:9px;font-weight:600}.hero{background:linear-gradient(135deg,#6366f1,#8b5cf6);color:white;padding:20px 14px;text-align:center}.hero h1{font-size:16px;font-weight:800;margin-bottom:5px}.hero p{font-size:10px;opacity:.8;margin-bottom:10px}.hero-cta{display:inline-block;background:white;color:#6366f1;padding:6px 16px;border-radius:7px;font-size:10px;font-weight:700}.grid{padding:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.card{background:white;border-radius:7px;overflow:hidden;border:1px solid #e2e8f0;box-shadow:0 1px 3px #0000000d}.card-thumb{height:40px;display:flex;align-items:center;justify-content:center;font-size:18px}.card-body{padding:7px}.card-name{font-size:10px;font-weight:700;color:#1e293b;margin-bottom:2px}.card-meta{font-size:8px;color:#94a3b8;margin-bottom:3px}.card-row{display:flex;align-items:center;justify-content:space-between}.card-price{font-size:11px;font-weight:800;color:#6366f1}.badge{background:#dcfce7;color:#16a34a;padding:1px 5px;border-radius:9px;font-size:7px;font-weight:700}</style></head><body><nav><span class="logo">⚡ EduPlatform</span><span class="nav-btn">Connexion</span></nav><div class="hero"><h1>Apprenez sans limites</h1><p>Plus de 200 cours en tech, business et design</p><span class="hero-cta">Voir tous les cours →</span></div><div class="grid"><div class="card"><div class="card-thumb" style="background:#fef3c7">📱</div><div class="card-body"><div class="card-name">React Native Pro</div><div class="card-meta">42 leçons · 8h</div><div class="card-row"><span class="card-price">197 €</span><span class="badge">NOUVEAU</span></div></div></div><div class="card"><div class="card-thumb" style="background:#dbeafe">🤖</div><div class="card-body"><div class="card-name">IA pour les entreprises</div><div class="card-meta">28 leçons · 5h</div><div class="card-row"><span class="card-price">147 €</span><span class="badge">★ 4,9</span></div></div></div><div class="card"><div class="card-thumb" style="background:#f3e8ff">💰</div><div class="card-body"><div class="card-name">SaaS de zéro</div><div class="card-meta">56 leçons · 12h</div><div class="card-row"><span class="card-price">297 €</span><span class="badge">TOP</span></div></div></div></div></body></html>`,
  ],
};

/** Code lines shown in the “generating” phase — shared (mostly code / neutral) */
export const HERO_DEMO_CODE_LINES: readonly [readonly string[], readonly string[], readonly string[]] = [
  [
    "<!DOCTYPE html>",
    '<html lang="pt-BR">',
    "  <style>",
    "    :root { --primary: #ff6b6b; --dark: #0d0d0d; }",
    "    body { background: var(--dark); color: #f5f5f5; }",
    "    .hero { min-height: 100vh; display: flex;",
    "      align-items: center; justify-content: center; }",
    "    h1 { font-size: clamp(2rem,6vw,5rem);",
    "         color: var(--primary); }",
    "    .btn { padding: 12px 28px; border-radius: 4px; }",
    "  </style>",
    "  <body>",
    "    <nav>🌸 SAKURA Restaurant</nav>",
    '    <div class="hero">',
    "      <h1>Sabores do Japão</h1>",
    "    </div>",
    "  </body>",
    "</html>",
  ],
  [
    "// Dashboard Analytics Component",
    "export default function Dashboard() {",
    "  const [stats] = useState([",
    "    { label: 'MRR', value: 'R$48.290', change: '+12%' },",
    "    { label: 'Usuários', value: '1.847', change: '+8%' },",
    "    { label: 'Churn', value: '2.4%', change: '-0.3%' },",
    "    { label: 'NPS', value: '78', change: '+5' },",
    "  ])",
    "  return (",
    "    <main className='dashboard'>",
    "      <StatsGrid stats={stats} />",
    "      <RevenueChart data={monthlyData} />",
    "      <UserTable users={recentUsers} />",
    "    </main>",
    "  )",
    "}",
  ],
  [
    "// app/api/courses/route.ts",
    "export async function GET() {",
    "  const courses = await db",
    "    .select('c.*, COUNT(e.id) as enrolled')",
    "    .from('courses c')",
    "    .leftJoin('enrollments e', 'c.id = e.course_id')",
    "    .where({ published: true })",
    "    .orderBy('enrolled', 'desc')",
    "  return Response.json(courses)",
    "}",
    "",
    "export async function POST(req: Request) {",
    "  const { courseId } = await req.json()",
    "  const session = await stripe.checkout.sessions.create({",
    "    line_items: [{ price: courseId, quantity: 1 }],",
    "    mode: 'payment',",
    "  })",
    "  return Response.json({ url: session.url })",
    "}",
  ],
] as const;
